
version: "3.8"
services:
  chatbox:
    image: tommy6769/chatbox:latest
    build: .
    container_name: chatbox
    ports:
      - "80:3700"
    environment: 
      - PORT=3700
    volumes: 
      - ./:/app
    command: ["node", "index.js"]
