
version: "3.8"
services:
  levichat:
    image: tommy6769/levichat:latest
    build: .
    container_name: levichat
    ports:
      - "80:3700"
    environment: 
      - PORT=3700
    volumes: 
      - ./:/app
    command: ["node", "index.js"]
